### ISSUE TITLE
代码格式好像有点奇怪

### ISSUE THREAD

**Issue by zaoqi** [USTC-Resource/USTC-Course#11]
https://github.com/USTC-Resource/USTC-Course/blob/master/c%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1/%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A12-lab/10C.cc

**Comment by zaoqi** [comment]
甚至有加号一边有空格一边没有

**Comment by mbinary** [comment]
emmm, 确实. 以前写的代码很不规范, 不过可以用代码格式化工具规范一下.

**Comment by mbinary** [comment]
用 astyle 格式化了一下文件   1122f52
