### ISSUE TITLE
PPT

### ISSUE THREAD

**Issue by wuyangkang** [USTC-Resource/USTC-Course#14]
你好同学，请问有配套资料的PPT或者其它学习资料么，谢谢。

**Comment by INDEXZEROING** [comment]
请问您说的是什么PPT或学习资料呢？



---Original---

**Comment by sadhen** [comment]
老师制作的slides应该是不能随便分享的，另外，其实很多课程的slides在课程主页上是有的

**Comment by INDEXZEROING** [comment]
???啥时候分享了？



---Original---
