### ISSUE TITLE
徐云老师的算法基础电子课件看不了，提示要密码

### ISSUE THREAD

**Issue by sukai-cheng** [USTC-Resource/USTC-Course#15]
<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by zyyyyyyyyyyyyyyyyy** [comment]
那提示密码是？
谢谢了🙏

**Comment by mbinary** [comment]
密码每学期都在变动, 所以抱歉非选课学生看不了课件

**Comment by zyyyyyyyyyyyyyyyyy** [comment]
太难了吧！

**Comment by sukai-cheng** [comment]
可以将课件分享给我吗？非常感谢了

zyyyyyyyyyyyyyyyyy <notifications@github.com> 于2019年11月4日周一 下午6:45写道：

> 太难了吧！
>
>
> Sent from my iPad
>
