### ISSUE TITLE
获取对应课程的书名或教材信息

### ISSUE THREAD

**Issue by heroye0919** [USTC-Resource/USTC-Course#22]
Dear USTC:
  很感谢提供的open-sources资源，本想看看issues的模板，发现没找到，只能通过readme的超链接过来，我想咨询一下这里对应课程的书名或教材信息，或推荐课程？感谢！

**Comment by mbinary** [comment]
这里的课程有些是用的本校的教材。如果想学哪门课，可以直接在网上搜索更容易找到的教材

**Comment by ycdxsb** [comment]
课程和教材可以在这里搜到 https://catalog.ustc.edu.cn/query/lesson
