### ISSUE TITLE
有网盘链接嘛？我想存下来

### ISSUE THREAD

**Issue by TTmiracle** [USTC-Resource/USTC-Course#26]
这个链接不咋熟悉

**Comment by heqin-zhu** [comment]
[点击下载](https://github.com/USTC-Resource/USTC-Course/archive/refs/heads/master.zip)

**Comment by TTmiracle** [comment]
这个可以下载！万分感谢！（悄悄问一哈：哈哈哈还有其他补充资料包吗？噗嘻嘻）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "USTC-Resource/USTC-Course"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 晚上10:28
***@***.***&gt;;
抄送:&nbsp;"天空 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [USTC-Resource/USTC-Course] 有网盘链接嘛？我想存下来 (Issue #26)





 
试试这个链接
