### ISSUE TITLE
近世代数课程资料

### ISSUE THREAD

**Issue by iw17** [USTC-Resource/USTC-Course#30]
我是2023年春季学期数院近世代数张班助教，整理了一学期的![作业答案](https://jsds.iw17.cc)，![TeX源码](https://github.com/iw17/jsds)在GitHub上也有，给我班同学期末复习用，不知道对您这个项目有没有帮助。

**Comment by heqin-zhu** [comment]
挺好的，我可以添加个链接到你仓库: jsds 这个仓库对吧
